author:
  name: Adam Harasansky
  email: harasansky@gmail.com
title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1308244
  brandStrength: 0.2522291995119303
  lightness: 0.9175627
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  rhythmicContrast: 0.6326165
typography_spectrum: 0.7706093
layout_spectrum: 0.202509
name: Intersection
